services:
  stage-alert:
    labels:
        com.centurylinklabs.watchtower.enable: "true"
    pull_policy: always
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    image: ghcr.io/slumberdac/internship-alert-async:latest
    shm_size: 1gb
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb
    environment:
      - TZ=America/Toronto
      - COOKIE=${COOKIE}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - CV_JSON=${CV_JSON}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_ROLE_ID=${DISCORD_ROLE_ID}
      - POSTES_PATH=${POSTES_PATH}
      - DELAY=${DELAY}
      - ACCOUNT=${ACCOUNT}
      - RANGE=${RANGE}
    volumes:
      - data:/data
      - /run/pcscd:/run/pcscd
    restart: unless-stopped
    ulimits:
      core: 0

  watchtower:
    image: containrrr/watchtower:arm64v8-latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_API_VERSION=1.52
    command: --cleanup --interval 30

volumes:
  data: {}